name: kcjostudio
favicon: null
layout_spectrum: 0.30155861121602356
typography_spectrum: 0.8929471310693771
title: Kacie Jo Mara Nickles Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.869332576636225
  lightness: 0.15252077160403132
  saturation: 0.023259540554136038
  rhythmicContrast: 0.3186969819944352
purpose: []
